version: '3'

# This docker-compose is for developer convenience and testing, not for running in production.

services:

  # General python container for executing tests
  spec:
    build: .
    volumes:
      - ${PWD}:/app
    depends_on:
      - re_api
    environment:
      - DB_URL=http://arangodb:8529
      - DB_USER=root
      - RE_API_URL=http://re_api:5000

  # Relation Engine API
  re_api:
    image: kbase/relation_engine_api:develop
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - arangodb
      - auth
      - workspace
    environment:
      - WORKERS=2
      - DEVELOPMENT=1
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - KBASE_AUTH_URL=http://auth:5000
      - KBASE_WORKSPACE_URL=http://workspace:5000
      - PYTHONUNBUFFERED=true
      - DB_URL=http://arangodb:8529
      - DB_USER=root
    volumes:
      - ".:/spec/repo"

  # Arangodb server in cluster mode
  arangodb:
    image: arangodb:3.4
    ports:
      - "127.0.0.1:8529:8529"
    command: sh -c "arangodb create jwt-secret --secret=jwtSecret &&
                    arangodb --starter.local --auth.jwt-secret=./jwtSecret"

  # A mock kbase auth server (see src/test/mock_auth/endpoints.json)
  auth:
    image: mockservices/mock_json_service
    volumes:
      - ${PWD}/test/mock_services/mock_auth:/config

  # Mock workspace server (see src/test/mock_workspace/endpoints.json)
  workspace:
    image: mockservices/mock_json_service
    volumes:
      - ${PWD}/test/mock_services/mock_workspace:/config
